# train_test config
lr: 1e-3
batch_size: 256
test_size: 0.2
val_size: 0.25
num_epochs: 15
optimizer: AdamW
weight_decay: 0.01
patience: 1000
evaluate_interval: 5
signal_length: 128
plot: False
compile_flag: False
compile:
  mode: default
  fullgraph: False
  dynamic: null

# network config
num_classes: 11
extend_channel: 36
latent_dim: 512
num_heads: 2
conv_chan_list: null
